
dotenv: .env

dependencies:
#    - aave/protocol-v2@1.0.1
    - aave/core-v3 v1.16.0
compiler:
    solc:
        remappings:
            - "@aave=aave/core-v3 v1.16.0"


networks:
  rinkeby: 
    pool_addr_provider: '0xA55125A90d75a95EC00130E8E8C197dB5641Eb19'
    weth: '0xc778417E063141139Fce010982780140Aa0cD5Ab'
    dai: '0x2Ec4c6fCdBF5F9beECeB1b51848fc2DB1f3a26af'
  
  mainnet-fork:
    pool_addr_provider: ''
    weth: ''
    dai: ''

  polygon-main-fork: ''
    pool_addr_provider: ''
    weth: ''
    dai: ''

  polygon-main: ''
    pool_addr_provider: ''
    weth: ''
    dai: ''

  polygon-test: ''
    pool_addr_provider: '0x5343b5bA672Ae99d627A1C87866b8E53F47Db2E6'
    weth: ''
    dai: '0xC87385b5E62099f92d490750Fcd6C901a524BBcA'




